name: GitHub Actions Demo
run-name: Code checks
on:
  pull_request:
    types: [opened, edited]
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v4
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install deps
        run: npm i
      - name: Check types
        run: npm run lint:types
      - name: Start tests
        run: npm test
      - run: echo "🍏 This job's status is ${{ job.status }}."
